name: luxy
description: "A Flutter application that allow you to customize your clothes"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.65.0
  flutter_animate: ^4.3.0
  hive: ^2.2.3
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  icons_plus: ^5.0.0
  path_provider: ^2.1.1
  fluttertoast: ^8.2.4
  lottie: ^2.7.0
  animated_toggle_switch: ^0.8.0
  cached_network_image: ^3.3.0
  intl_phone_number_input: ^0.7.4
  otp_text_field: ^1.1.3
  date_format: ^2.0.7
  url_launcher: ^6.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  http: ^1.1.2
  file_picker: ^6.1.1
  firebase_ui_firestore: ^1.5.15
  image_picker: ^1.0.5
  voice_message_package: ^2.1.4
  mime: ^1.0.4
  open_filex: ^4.3.4
  social_media_recorder: ^1.1.12
  cool_dropdown: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/pictures/
    - assets/jsons/
