name: luxy
description: "A Flutter application that allow you to customize your clothes"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.65.0
  flutter_animate: ^4.3.0
  get: ^4.6.6
  hive: ^2.2.3
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  icons_plus: ^5.0.0
  path_provider: ^2.1.1
  fluttertoast: ^8.2.4
  lottie: ^2.7.0
  animated_toggle_switch: ^0.8.0
  cached_network_image: ^3.3.0
  intl_phone_number_input: ^0.7.4
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/pictures/
    - assets/jsons/
